const team = {
  tampa: {
    'Ryan Callahan': {
      name: 'Ryan Callahan',
      position: 'Forward',
      goals: 6,
      assists: 9,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8471339.jpg',
    },
    'Anthony Cirelli': {
      name: 'Anthony Cirelli',
      position: 'Forward',
      goals: 13,
      assists: 14,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478519.jpg',
    },
    'Adam Erne': {
      name: 'Adam Erne',
      position: 'Forward',
      goals: 6,
      assists: 10,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477454.jpg',
    },
    'Yanni Gourde': {
      name: 'Yanni Gourde',
      position: 'Forward',
      goals: 17,
      assists: 21,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476826.jpg',
    },
    'Tyler Johnson': {
      name: 'Tyler Johnson',
      position: 'Forward',
      goals: 22,
      assists: 17,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474870.jpg',
    },
    'Mathie Joseph': {
      name: 'Mathie Joseph',
      position: 'Forward',
      goals: 13,
      assists: 7,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478472.jpg',
    },
    'Alex Killorn': {
      name: 'Alex Killorn',
      position: 'Forward',
      goals: 13,
      assists: 20,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8473986.jpg',
    },
    'Nikita Kucherov': {
      name: 'Nikita Kucherov',
      position: 'Forward',
      goals: 31,
      assists: 75,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476453.jpg',
    },
    'Danick Martel': {
      name: 'Danick Martel',
      position: 'Forward',
      goals: 0,
      assists: 2,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478365.jpg',
    },
    'J.T. Miller': {
      name: 'J.T. Miller',
      position: 'Forward',
      goals: 12,
      assists: 24,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476468.jpg',
    },
    'Ondrej Palat': {
      name: 'Ondrej Palat',
      position: 'Forward',
      goals: 7,
      assists: 20,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476292.jpg',
    },
    'Cedric Paquette': {
      name: 'Cedric Paquette',
      position: 'Forward',
      goals: 9,
      assists: 4,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476975.jpg',
    },
    'Brayden Point': {
      name: 'Brayden Point',
      position: 'Forward',
      goals: 36,
      assists: 44,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478010.jpg',
    },
    'Steven Stamkos': {
      name: 'Steven Stamkos',
      position: 'Forward',
      goals: 33,
      assists: 44,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474564.jpg',
    },
    'Erik Cernak': {
      name: 'Erik Cernak',
      position: 'Defense',
      goals: 3,
      assists: 8,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478416.jpg',
    },
    'Braydon Coburn': {
      name: 'Braydon Coburn',
      position: 'Defense',
      goals: 3,
      assists: 15,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8470601.jpg',
    },
    'Dan Giradi': {
      name: 'Dan Giradi',
      position: 'Defense',
      goals: 4,
      assists: 10,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8471958.jpg',
    },
    'Victor Hedman': {
      name: 'Victor Hedman',
      position: 'Defense',
      goals: 9,
      assists: 32,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8475167.jpg',
    },
    'Ryan McDonagh': {
      name: 'Ryan McDonagh',
      position: 'Defense',
      goals: 7,
      assists: 26,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474151.jpg',
    },
    'Mikhail Sergachev': {
      name: 'Mikhail Sergachev',
      position: 'Defense',
      goals: 5,
      assists: 18,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8479410.jpg',
    },
    'Anton Stralman': {
      name: 'Anton Stralman',
      position: 'Defense',
      goals: 2,
      assists: 15,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8471873.jpg',
    },
  },
  flames: {
    'Mikael Backlund': {
      name: 'Mikael Backlund',
      position: 'Forward',
      goals: 17,
      assists: 22,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474150.jpg',
    },
    'Sam Bennet': {
      name: 'Sam Bennet',
      position: 'Forward',
      goals: 11,
      assists: 13,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477935.jpg',
    },
    'Austin Czarnik': {
      name: 'Austin Czarnik',
      position: 'Forward',
      goals: 6,
      assists: 5,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478512.jpg',
    },
    'Michael Frolik': {
      name: 'Michael Frolik',
      position: 'Forward',
      goals: 13,
      assists: 10,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8473564.jpg',
    },
    'Johnny Gaudrea': {
      name: 'Johnny Gaudrea',
      position: 'Forward',
      goals: 30,
      assists: 53,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476346.jpg',
    },
    'Garnet Hathaway': {
      name: 'Garnet Hathaway',
      position: 'Forward',
      goals: 7,
      assists: 3,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477903.jpg',
    },
    'Mark Jankowski': {
      name: 'Mark Jankowski',
      position: 'Forward',
      goals: 10,
      assists: 15,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476873.jpg',
    },
    'Elias Lindholm': {
      name: 'Elias Lindholm',
      position: 'Forward',
      goals: 26,
      assists: 46,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477496.jpg',
    },
    'Andrew M.': {
      name: 'Andrew M.',
      position: 'Forward',
      goals: 3,
      assists: 2,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478233.jpg',
    },
    'Sean Monahan': {
      name: 'Sean Monahan',
      position: 'Forward',
      goals: 30,
      assists: 40,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477497.jpg',
    },
    'James Neal': {
      name: 'James Neal',
      position: 'Forward',
      goals: 5,
      assists: 10,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8471707.jpg',
    },
    'Derek Ryan': {
      name: 'Derek Ryan',
      position: 'Forward',
      goals: 6,
      assists: 18,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478585.jpg',
    },
    'Matthew Tkachuk': {
      name: 'Matthew Tkachuk',
      position: 'Forward',
      goals: 25,
      assists: 36,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8479314.jpg',
    },
    'Rasmus Andersson': {
      name: 'Rasmus Andersson',
      position: 'Defense',
      goals: 2,
      assists: 11,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478397.jpg',
    },
    'TJ Brodie': {
      name: 'TJ Brodie',
      position: 'Defense',
      goals: 8,
      assists: 23,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474673.jpg',
    },
    'Oscar Fantenberg': {
      name: 'Oscar Fantenberg',
      position: 'Defense',
      goals: 2,
      assists: 1,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8480147.jpg',
    },
    'Mark Giordano': {
      name: 'Mark Giordano',
      position: 'Defense',
      goals: 14,
      assists: 47,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8470966.jpg',
    },
    'Travis Hamonic': {
      name: 'Travis Hamonic',
      position: 'Defense',
      goals: 6,
      assists: 9,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474612.jpg',
    },
    'Oliver Kylingto': {
      name: 'Oliver Kylingto',
      position: 'Defense',
      goals: 3,
      assists: 4,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478430.jpg',
    },
    'Dalton Prout': {
      name: 'Dalton Prout',
      position: 'Defense',
      goals: 0,
      assists: 1,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474774.jpg',
    },
    'Michael Stone': {
      name: 'Michael Stone',
      position: 'Defense',
      goals: 0,
      assists: 4,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474628.jpg',
    },
  },
  bruins: {
    'Noel Acciari': {
      name: 'Noel Acciari',
      position: 'Forward',
      goals: 3,
      assists: 5,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478569.jpg',
    },
    'David Backes': {
      name: 'David Backes',
      position: 'Forward',
      goals: 5,
      assists: 9,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8470655.jpg',
    },
    'Patrice Bergeron': {
      name: 'Patrice Bergeon',
      position: 'Forward',
      goals: 22,
      assists: 36,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8470638.jpg',
    },
    'Peter Cehlarik': {
      name: 'Peter Cehlarik',
      position: 'Forward',
      goals: 4,
      assists: 2,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477417.jpg',
    },
    'Charlie Coyle': {
      name: 'Charlie Coyle',
      position: 'Forward',
      goals: 10,
      assists: 18,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8475745.jpg',
    },
    'Jake Debrusk': {
      name: 'Jake Debrusk',
      position: 'Forward',
      goals: 21,
      assists: 10,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478498.jpg',
    },
    'Danton Heinen': {
      name: 'Danton Heinen',
      position: 'Forward',
      goals: 9,
      assists: 15,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478046.jpg',
    },
    'Marcus Johansson': {
      name: 'Marcus Johansson',
      position: 'Forward',
      goals: 12,
      assists: 16,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8475149.jpg',
    },
    'David Krejci': {
      name: 'David Krejci',
      position: 'Forward',
      goals: 15,
      assists: 40,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8471276.jpg',
    },
    'Sean Kuraly': {
      name: 'Sean Kuraly',
      position: 'Forward',
      goals: 6,
      assists: 11,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476374.jpg',
    },
    'Brad Marchand': {
      name: 'Brad Marchand',
      position: 'Forward',
      goals: 26,
      assists: 49,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8473419.jpg',
    },
    'Joakim Nordstrom': {
      name: 'Joakim Nordstrom',
      position: 'Forward',
      goals: 5,
      assists: 2,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8475807.jpg',
    },
    'David Pastrnak': {
      name: 'David Pastrnak',
      position: 'Forward',
      goals: 31,
      assists: 35,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8477956.jpg',
    },
    'Chris Wagner': {
      name: 'Chris Wagner',
      position: 'Forward',
      goals: 9,
      assists: 6,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8475780.jpg',
    },
    'Brandon Carlo': {
      name: 'Brandon Carlo',
      position: 'Defense',
      goals: 1,
      assists: 5,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8478443.jpg',
    },
    'Zdeno Chara': {
      name: 'Zdeno Chara',
      position: 'Defense',
      goals: 3,
      assists: 19,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8465009.jpg',
    },
    'Matt Grzelcyk': {
      name: 'Matt Grzelcyk',
      position: 'Defense',
      goals: 1,
      assists: 13,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476891.jpg',
    },
    'Steven Kampfer': {
      name: 'Steven Kampfer',
      position: 'Defense',
      goals: 2,
      assists: 1,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8474000.jpg',
    },
    'Torey Krug': {
      name: 'Torey Krug',
      position: 'Defense',
      goals: 6,
      assists: 40,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476792.jpg',
    },
    'Charlie McAvoy': {
      name: 'Charlie McAvoy',
      position: 'Defense',
      goals: 5,
      assists: 14,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8479325.jpg',
    },
    'Kevan Miller': {
      name: 'Kevan Miller',
      position: 'Defense',
      goals: 0,
      assists: 6,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8476191.jpg',
    },
    'John Moore': {
      name: 'John Moore',
      position: 'Defense',
      goals: 3,
      assists: 7,
      img: 'https://nhl.bamcontent.com/images/headshots/current/168x168/8475186.jpg',
    },
  },
};

module.exports = {
  team,
};
